### ISSUE TITLE
Assemble Opcode reports instruction number, rather than line number when there is error

### ISSUE THREAD

**Issue by PythonGuython** [Herring-UGACSEE-4290/Project-3#5]
Reproduce by parsing "../tests/BabyTest.asm"

will output:
Missing mnemonic for line 0. Skipping instruction. Error: Could not determine if line is instruction or label
Missing mnemonic for line 1. Skipping instruction. Error: Could not determine if line is instruction or label
Missing mnemonic for line 2. Skipping instruction. Error: Could not determine if line is instruction or label

We know this is not true because there is no instruction on lines 0, 1, or 2. Also, line 0 does not exist.

The line dictionary has a "line number" field. This is different than the index in the list of line dictionaries because indexing starts at 0 and doesn't include whitespace.

**Comment by MichaelStarks** [comment]
Changed the string format to use the line number field from the line dictionary instead of the enumeration index.

**Comment by MichaelStarks** [comment]
Issue resolved. 8806e318c9ad150dff2a3218b4b9cbf583257329
