### ISSUE TITLE
ORG does not assemble correctly

### ISSUE THREAD

**Issue by PythonGuython** [Herring-UGACSEE-4290/Project-3#9]
To reproduce, assemble to following program:
```
starting:
    ADD r1,r2,r3
    ORG #0x4
    HALT
```

The following error is printed to the console:
`Instruction ORG on line 3 not found. Possible incorrect number of arguments`

**Comment by ktkoffroth** [comment]
did you try giving it a full 32-bit immediate? I don't know how you guys are handling those, @Jyumpp  would know more about how it's implemented.

**Comment by PythonGuython** [comment]
values are parsed as ints, then changed to hex at write time

**Comment by MichaelStarks** [comment]
The condition does not work because ORG does not have an opcode. It just sets the next address.  I have a fix but we can talk about it later cause I don't like it. @Jyumpp your still works.

**Comment by MichaelStarks** [comment]
Fixed 9d13ee70aec09ff368c384921282056573c57991
issue closed
